//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnaPrint.Config.dnaPrintWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="dnaPrintWS.IExecute")]
    public interface IExecute {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/Exec", ReplyAction="http://tempuri.org/IExecute/ExecResponse")]
        bool Exec(string key, string query, string[][] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/Exec", ReplyAction="http://tempuri.org/IExecute/ExecResponse")]
        System.Threading.Tasks.Task<bool> ExecAsync(string key, string query, string[][] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/RetornaValor", ReplyAction="http://tempuri.org/IExecute/RetornaValorResponse")]
        string RetornaValor(string key, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/RetornaValor", ReplyAction="http://tempuri.org/IExecute/RetornaValorResponse")]
        System.Threading.Tasks.Task<string> RetornaValorAsync(string key, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/ListarOids", ReplyAction="http://tempuri.org/IExecute/ListarOidsResponse")]
        string[][] ListarOids(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecute/ListarOids", ReplyAction="http://tempuri.org/IExecute/ListarOidsResponse")]
        System.Threading.Tasks.Task<string[][]> ListarOidsAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExecuteChannel : dnaPrint.Config.dnaPrintWS.IExecute, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteClient : System.ServiceModel.ClientBase<dnaPrint.Config.dnaPrintWS.IExecute>, dnaPrint.Config.dnaPrintWS.IExecute {
        
        public ExecuteClient() {
        }
        
        public ExecuteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecuteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Exec(string key, string query, string[][] parametros) {
            return base.Channel.Exec(key, query, parametros);
        }
        
        public System.Threading.Tasks.Task<bool> ExecAsync(string key, string query, string[][] parametros) {
            return base.Channel.ExecAsync(key, query, parametros);
        }
        
        public string RetornaValor(string key, string query) {
            return base.Channel.RetornaValor(key, query);
        }
        
        public System.Threading.Tasks.Task<string> RetornaValorAsync(string key, string query) {
            return base.Channel.RetornaValorAsync(key, query);
        }
        
        public string[][] ListarOids(string key) {
            return base.Channel.ListarOids(key);
        }
        
        public System.Threading.Tasks.Task<string[][]> ListarOidsAsync(string key) {
            return base.Channel.ListarOidsAsync(key);
        }
    }
}
