//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorEtqSuprimentos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dnaPrintEntities : DbContext
    {
        public dnaPrintEntities()
            : base("name=dnaPrintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("dnaPrintEntities", "Func_ProducaoCilindro")]
        public virtual IQueryable<Func_ProducaoCilindro_Result> Func_ProducaoCilindro(string serialCilindro)
        {
            var serialCilindroParameter = serialCilindro != null ?
                new ObjectParameter("SerialCilindro", serialCilindro) :
                new ObjectParameter("SerialCilindro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_ProducaoCilindro_Result>("[dnaPrintEntities].[Func_ProducaoCilindro](@SerialCilindro)", serialCilindroParameter);
        }
    }
}
