//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorEtqSuprimentos.wsEtqSuprimentos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_EtiquetasSuprimentos", Namespace="http://schemas.datacontract.org/2004/07/EtiquetasSuprimentosService")]
    [System.SerializableAttribute()]
    public partial class vw_EtiquetasSuprimentos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ValorAtualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dtTerminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dtTrocaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etiquetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> producaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serialSuprimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suprimentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((this.GrupoField.Equals(value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ValorAtual {
            get {
                return this.ValorAtualField;
            }
            set {
                if ((this.ValorAtualField.Equals(value) != true)) {
                    this.ValorAtualField = value;
                    this.RaisePropertyChanged("ValorAtual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dtTermino {
            get {
                return this.dtTerminoField;
            }
            set {
                if ((this.dtTerminoField.Equals(value) != true)) {
                    this.dtTerminoField = value;
                    this.RaisePropertyChanged("dtTermino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dtTroca {
            get {
                return this.dtTrocaField;
            }
            set {
                if ((this.dtTrocaField.Equals(value) != true)) {
                    this.dtTrocaField = value;
                    this.RaisePropertyChanged("dtTroca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                if ((object.ReferenceEquals(this.etiquetaField, value) != true)) {
                    this.etiquetaField = value;
                    this.RaisePropertyChanged("etiqueta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                if ((object.ReferenceEquals(this.operadorField, value) != true)) {
                    this.operadorField = value;
                    this.RaisePropertyChanged("operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> producao {
            get {
                return this.producaoField;
            }
            set {
                if ((this.producaoField.Equals(value) != true)) {
                    this.producaoField = value;
                    this.RaisePropertyChanged("producao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serialSuprimento {
            get {
                return this.serialSuprimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.serialSuprimentoField, value) != true)) {
                    this.serialSuprimentoField = value;
                    this.RaisePropertyChanged("serialSuprimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string suprimento {
            get {
                return this.suprimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.suprimentoField, value) != true)) {
                    this.suprimentoField = value;
                    this.RaisePropertyChanged("suprimento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEtqSuprimentos.IEtiquetasSuprimentos")]
    public interface IEtiquetasSuprimentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/Listar", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/ListarResponse")]
        MonitorEtqSuprimentos.wsEtqSuprimentos.vw_EtiquetasSuprimentos[] Listar(string key, string Status, int idLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/Listar", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/ListarResponse")]
        System.Threading.Tasks.Task<MonitorEtqSuprimentos.wsEtqSuprimentos.vw_EtiquetasSuprimentos[]> ListarAsync(string key, string Status, int idLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarProducao", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarProducaoResponse")]
        void AtualizarProducao(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarProducao", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarProducaoResponse")]
        System.Threading.Tasks.Task AtualizarProducaoAsync(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTroca", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTrocaResponse")]
        void AtualizarTroca(string key, string CRUM, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTroca", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTrocaResponse")]
        System.Threading.Tasks.Task AtualizarTrocaAsync(string key, string CRUM, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTermino", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTerminoResponse")]
        void AtualizarTermino(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTermino", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/AtualizarTerminoResponse")]
        System.Threading.Tasks.Task AtualizarTerminoAsync(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/QuantidadeListas", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/QuantidadeListasResponse")]
        long QuantidadeListas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtiquetasSuprimentos/QuantidadeListas", ReplyAction="http://tempuri.org/IEtiquetasSuprimentos/QuantidadeListasResponse")]
        System.Threading.Tasks.Task<long> QuantidadeListasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEtiquetasSuprimentosChannel : MonitorEtqSuprimentos.wsEtqSuprimentos.IEtiquetasSuprimentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtiquetasSuprimentosClient : System.ServiceModel.ClientBase<MonitorEtqSuprimentos.wsEtqSuprimentos.IEtiquetasSuprimentos>, MonitorEtqSuprimentos.wsEtqSuprimentos.IEtiquetasSuprimentos {
        
        public EtiquetasSuprimentosClient() {
        }
        
        public EtiquetasSuprimentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtiquetasSuprimentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetasSuprimentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtiquetasSuprimentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MonitorEtqSuprimentos.wsEtqSuprimentos.vw_EtiquetasSuprimentos[] Listar(string key, string Status, int idLista) {
            return base.Channel.Listar(key, Status, idLista);
        }
        
        public System.Threading.Tasks.Task<MonitorEtqSuprimentos.wsEtqSuprimentos.vw_EtiquetasSuprimentos[]> ListarAsync(string key, string Status, int idLista) {
            return base.Channel.ListarAsync(key, Status, idLista);
        }
        
        public void AtualizarProducao(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual) {
            base.Channel.AtualizarProducao(key, CRUM, data, Producao, ValorAtual);
        }
        
        public System.Threading.Tasks.Task AtualizarProducaoAsync(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual) {
            return base.Channel.AtualizarProducaoAsync(key, CRUM, data, Producao, ValorAtual);
        }
        
        public void AtualizarTroca(string key, string CRUM, System.DateTime data) {
            base.Channel.AtualizarTroca(key, CRUM, data);
        }
        
        public System.Threading.Tasks.Task AtualizarTrocaAsync(string key, string CRUM, System.DateTime data) {
            return base.Channel.AtualizarTrocaAsync(key, CRUM, data);
        }
        
        public void AtualizarTermino(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual) {
            base.Channel.AtualizarTermino(key, CRUM, data, Producao, ValorAtual);
        }
        
        public System.Threading.Tasks.Task AtualizarTerminoAsync(string key, string CRUM, System.DateTime data, int Producao, int ValorAtual) {
            return base.Channel.AtualizarTerminoAsync(key, CRUM, data, Producao, ValorAtual);
        }
        
        public long QuantidadeListas() {
            return base.Channel.QuantidadeListas();
        }
        
        public System.Threading.Tasks.Task<long> QuantidadeListasAsync() {
            return base.Channel.QuantidadeListasAsync();
        }
    }
}
