<%@ Page Language="C#" MasterPageFile="~/AppSiteMaster.Master" AutoEventWireup="true" CodeFile="Configuracao.aspx.cs" Inherits="Configuracao" Title="CSF Digital" %>
<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Cabecalho" ContentPlaceHolderID="ContentPlaceHolderCabecalho" runat="server">
    <div class="menuHome">  
        <a href="Home.aspx" class="link">home</a>      	
    </div>
    <div class="menuRelatorio">  
        <a href="Relatorio.aspx" class="link">relatorio</a>      	
    </div>
    <div class="menuMonitor">  
        <a href="Monitor.aspx" class="link">monitor</a>      	
    </div>
    <div class="menuConfiguracaoAtivo">  
        <a href="Configuracao.aspx" class="link">configuracao</a>      	
    </div>
    <div class="menuSuporte">  
        <a href="Suporte.aspx" class="link">suporte</a>      	
    </div>
</asp:Content>
<asp:Content ID="Corpo" ContentPlaceHolderID="ContentPlaceHolderCorpo" runat="server">
    <asp:ScriptManagerProxy ID="ScriptManagerProxy1" runat="server"></asp:ScriptManagerProxy>
    <div id="conteudoCentro" runat="server" style="margin: -7px 135px;" >
        <table class= "content" width="100%">
            <tr>
                <td align="left" valign="top" width="100%">
                    <telerik:RadTabStrip ID="RadTabStrip1" runat="server" Skin="Vista" MultiPageID="RadMultiPage1" SelectedIndex="0" Align="Justify" ReorderTabsOnSelect="true" Width="100%">
                    <Tabs>
                        <telerik:RadTab Text="Parâmetros">
                        </telerik:RadTab>
                        <telerik:RadTab Text="Avisos">
                        </telerik:RadTab>
                        <telerik:RadTab Text="SLA's">
                        </telerik:RadTab>
                        <telerik:RadTab Text="Chaves">
                        </telerik:RadTab>
                        <telerik:RadTab Text="Feriados">
                        </telerik:RadTab>
                    </Tabs>
                    </telerik:RadTabStrip>
                    <telerik:RadMultiPage ID="RadMultiPage1" runat="server" SelectedIndex="0" CssClass="pageView" Width="100%">
                        <telerik:RadPageView ID="RadPageView1" runat="server">
                            <telerik:RadGrid ID="RadGrid1" runat="server" CellSpacing="0" 
                                GridLines="Horizontal" DataSourceID="ObjectDataSourceParametros" 
                                AutoGenerateColumns="False" GroupingEnabled="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid1_NeedDataSource"
                                OnDeleteCommand="RadGrid1_DeleteCommand" 
                                OnInsertCommand="RadGrid1_InsertCommand" 
                                OnUpdateCommand="RadGrid1_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    DataSourceID="ObjectDataSourceParametros" CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar novo parâmetro" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Nome" FilterControlAltText="Filter Nome column" HeaderText="Nome" SortExpression="Nome" UniqueName="Nome" AllowFiltering="False" AllowSorting="False">
                                            <FooterStyle Width="250px" Wrap="False" />
                                            <HeaderStyle Width="250px" Wrap="False" />
                                            <ItemStyle Width="250px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Valor" FilterControlAltText="Filter Valor column" HeaderText="Valor" SortExpression="Valor" UniqueName="Valor" AllowFiltering="False" AllowSorting="False">
                                            <FooterStyle Width="250px" Wrap="False" />
                                            <HeaderStyle Width="250px" Wrap="False" />
                                            <ItemStyle Width="250px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                    </Columns>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar parâmetro {0}" CaptionDataField="Nome">  
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <%--<FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle> --%>
                                        <FormMainTableStyle CellSpacing="0" CellPadding="3" Width="100%" /> 
                                        <FormTableStyle GridLines="Horizontal" CellSpacing="0" CellPadding="2" CssClass="module" Height="110px" Width="100%" /> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormStyle Width="100%" BackColor="#EEF2EA"></FormStyle> 
                                        <EditColumn EditText="Alterar" UpdateText="Confirmar" UniqueName="EditCommandColumn1" CancelText="Cancelar"></EditColumn>
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings> 
                                </MasterTableView>
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>
                            <asp:ObjectDataSource ID="ObjectDataSourceParametros" runat="server" 
                                SelectMethod="RetornaParametros" TypeName="CSFDigital.Controls.Parametro">
                            </asp:ObjectDataSource>
                        </telerik:RadPageView>
                        <telerik:RadPageView ID="RadPageView2" runat="server">
                            <telerik:RadGrid ID="RadGrid2" runat="server" CellSpacing="0" 
                                GridLines="Horizontal" 
                                AutoGenerateColumns="False" GroupingEnabled="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid2_NeedDataSource"
                                OnDeleteCommand="RadGrid2_DeleteCommand" 
                                OnInsertCommand="RadGrid2_InsertCommand" 
                                OnUpdateCommand="RadGrid2_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True" 
                                DataSourceID="ObjectDataSourceAvisos">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    DataSourceID="ObjectDataSourceAvisos" CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar novo aviso" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Id" FilterControlAltText="Filter Id column" 
                                            HeaderText="Id" SortExpression="Id" UniqueName="Id" DataType="System.Int32" ReadOnly="True">
                                            <FooterStyle Width="20px" Wrap="False" />
                                            <HeaderStyle Width="20px" Wrap="False" />
                                            <ItemStyle Width="20px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="CriadoEm" DataType="System.DateTime" 
                                            FilterControlAltText="Filter CriadoEm column" HeaderText="CriadoEm" 
                                            SortExpression="Criado Em" UniqueName="CriadoEm" ReadOnly="True" DataFormatString="{0:dd/MM/yyyy}">
                                            <FooterStyle Width="80px" Wrap="False" />
                                            <HeaderStyle Width="80px" Wrap="False" />
                                            <ItemStyle Width="80px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="CriadoPor" 
                                            FilterControlAltText="Filter CriadoPor column" HeaderText="CriadoPor" 
                                            SortExpression="Criado Por" UniqueName="CriadoPor" ReadOnly="True">
                                            <FooterStyle Width="300px" Wrap="False" />
                                            <HeaderStyle Width="300px" Wrap="False" />
                                            <ItemStyle Width="300px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Descricao" 
                                            FilterControlAltText="Filter Descricao column" HeaderText="Descricao" 
                                            SortExpression="Descricao" UniqueName="Descricao">
                                        </telerik:GridBoundColumn>
                                    </Columns>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar aviso {0}" CaptionDataField="Id">  
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <%--<FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle> --%>
                                        <FormMainTableStyle CellSpacing="0" CellPadding="3" Width="100%" /> 
                                        <FormTableStyle GridLines="Horizontal" CellSpacing="0" CellPadding="2" CssClass="module" Height="110px" Width="100%" /> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormStyle Width="100%" BackColor="#EEF2EA"></FormStyle> 
                                        <EditColumn EditText="Alterar" UpdateText="Confirmar" UniqueName="EditCommandColumn1" CancelText="Cancelar"></EditColumn> 
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings>
                                </MasterTableView>
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>                            
                            <asp:ObjectDataSource ID="ObjectDataSourceAvisos" runat="server" 
                                SelectMethod="RetornaAvisos" TypeName="CSFDigital.Controls.Aviso">
                            </asp:ObjectDataSource>
                        </telerik:RadPageView>
                        <telerik:RadPageView ID="RadPageView3" runat="server">
                            <telerik:RadGrid ID="RadGrid3" runat="server" CellSpacing="0" 
                                GridLines="Horizontal" 
                                AutoGenerateColumns="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid3_NeedDataSource"
                                OnDeleteCommand="RadGrid3_DeleteCommand" 
                                OnInsertCommand="RadGrid3_InsertCommand" 
                                OnUpdateCommand="RadGrid3_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True" 
                                DataSourceID="ObjectDataSourceSLAs" ShowGroupPanel="True">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <GroupPanel Text="">
                                </GroupPanel>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp" 
                                    DataSourceID="ObjectDataSourceSLAs" ShowFooter="True">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar novo SLA - Assistência Técnica" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Id" FilterControlAltText="Filter Id column" 
                                            HeaderText="Id" SortExpression="Id" UniqueName="Id" 
                                            DataType="System.Int32" ReadOnly="True">
                                            <FooterStyle Width="20px" Wrap="False" />
                                            <HeaderStyle Width="20px" Wrap="False" />
                                            <ItemStyle Width="20px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Local" DataType="System.Int32" 
                                            FilterControlAltText="Filter Local column" HeaderText="Local" 
                                            SortExpression="Local" UniqueName="Local">
                                            <FooterStyle Width="150px" Wrap="False" />
                                            <HeaderStyle Width="150px" Wrap="False" />
                                            <ItemStyle Width="150px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Prioridade" DataType="System.Int32" 
                                            FilterControlAltText="Filter Prioridade column" HeaderText="Prioridade" 
                                            SortExpression="Prioridade" UniqueName="Prioridade">
                                            <FooterStyle Width="100px" Wrap="False" />
                                            <HeaderStyle Width="100px" Wrap="False" />
                                            <ItemStyle Width="100px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Nivel" 
                                            FilterControlAltText="Filter Nivel column" HeaderText="Severidade" 
                                            SortExpression="Nivel" UniqueName="Nivel" DataType="System.Int32" 
                                            ReadOnly="True">
                                            <FooterStyle Width="150px" Wrap="False" />
                                            <HeaderStyle Width="150px" Wrap="False" />
                                            <ItemStyle Width="150px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="LimiteContingenciaFormatado" 
                                            FilterControlAltText="Filter LimiteContingenciaFormatado column" 
                                            HeaderText="Tempo Contingência" 
                                            SortExpression="LimiteContingenciaFormatado" 
                                            UniqueName="LimiteContingenciaFormatado">
                                            <FooterStyle Width="150px" Wrap="False" />
                                            <HeaderStyle Width="150px" Wrap="False" />
                                            <ItemStyle Width="150px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="LimiteFormatado" 
                                            FilterControlAltText="Filter LimiteFormatado column" 
                                            HeaderText="Tempo Final" ReadOnly="False" SortExpression="LimiteFormatado" 
                                            UniqueName="LimiteFormatado">
                                        </telerik:GridBoundColumn>
                                    </Columns>
                                    <GroupByExpressions>
                                        <telerik:GridGroupByExpression>
                                            <GroupByFields>
                                                <telerik:GridGroupByField  FieldAlias="Nivel" FieldName="Nivel" 
                                                    FormatString="" HeaderText="Severidade" SortOrder="Ascending" />
                                            </GroupByFields>
                                            <SelectFields>
                                                <telerik:GridGroupByField  FieldAlias="Nivel" FieldName="Nivel" 
                                                    FormatString="" HeaderText="Severidade" SortOrder="Ascending" />
                                            </SelectFields>
                                        </telerik:GridGroupByExpression>
                                    </GroupByExpressions>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar SLA {0}" CaptionDataField="Id">  
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <%--<FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle> --%>
                                        <FormMainTableStyle CellSpacing="0" CellPadding="3" Width="100%" /> 
                                        <FormTableStyle GridLines="Horizontal" CellSpacing="0" CellPadding="2" CssClass="module" Height="110px" Width="100%" /> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormStyle Width="100%" BackColor="#EEF2EA"></FormStyle> 
                                        <EditColumn EditText="Alterar" UpdateText="Confirmar" UniqueName="EditCommandColumn1" CancelText="Cancelar"></EditColumn> 
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings>
                                </MasterTableView>
                                <GroupingSettings CollapseTooltip="Recolher" ExpandTooltip="Expandir" GroupSplitDisplayFormat="Exibindo {0} de {1} itens." UnGroupButtonTooltip="Desagrupar" UnGroupTooltip="Arraste o item para fora da barra para desagrupar" />
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>                            
                            <asp:ObjectDataSource ID="ObjectDataSourceSLAs" runat="server" 
                                SelectMethod="SLA_AtendimentoTecnico" TypeName="CSFDigital.Controls.SLA">
                            </asp:ObjectDataSource>
                            <br />
                            <telerik:RadGrid ID="RadGrid4" runat="server" CellSpacing="0" 
                                GridLines="Horizontal" 
                                AutoGenerateColumns="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid4_NeedDataSource"
                                OnDeleteCommand="RadGrid4_DeleteCommand" 
                                OnInsertCommand="RadGrid4_InsertCommand" 
                                OnUpdateCommand="RadGrid4_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True" 
                                DataSourceID="ObjectDataSourceSLAs_Toner" ShowGroupPanel="True">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <GroupPanel Text="">
                                </GroupPanel>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp" 
                                    DataSourceID="ObjectDataSourceSLAs_Toner" ShowFooter="True">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar novo SLA - Toner" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                        <HeaderStyle Width="20px"></HeaderStyle>
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Id" FilterControlAltText="Filter Id column" 
                                            HeaderText="Id" SortExpression="Id" UniqueName="Id" DataType="System.Int32" ReadOnly="True">
                                            <FooterStyle Width="20px" Wrap="False" />
                                            <HeaderStyle Width="20px" Wrap="False" />
                                            <ItemStyle Width="20px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="LocalRegiao" DataType="System.Int32" 
                                            FilterControlAltText="Filter LocalRegiao column" HeaderText="Região" 
                                            SortExpression="LocalRegiao" UniqueName="LocalRegiao">
                                            <FooterStyle Width="150px" Wrap="False" />
                                            <HeaderStyle Width="150px" Wrap="False" />
                                            <ItemStyle Width="150px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Local" DataType="System.Int32" 
                                            FilterControlAltText="Filter Local column" HeaderText="Local" 
                                            SortExpression="Local" UniqueName="Local">
                                            <FooterStyle Width="150px" Wrap="False" />
                                            <HeaderStyle Width="150px" Wrap="False" />
                                            <ItemStyle Width="150px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="LimiteFormatado" 
                                            FilterControlAltText="Filter LimiteFormatado column" 
                                            HeaderText="Tempo Final" ReadOnly="False" SortExpression="LimiteFormatado" 
                                            UniqueName="LimiteFormatado">
                                        </telerik:GridBoundColumn>
                                    </Columns>
                                    <GroupByExpressions>
                                        <telerik:GridGroupByExpression>
                                            <GroupByFields>
                                                <telerik:GridGroupByField  FieldAlias="LocalRegiao" FieldName="LocalRegiao" 
                                                    FormatString="" HeaderText="Região" SortOrder="Ascending" />
                                            </GroupByFields>
                                            <SelectFields>
                                                <telerik:GridGroupByField  FieldAlias="LocalRegiao" FieldName="LocalRegiao" 
                                                    FormatString="" HeaderText="Região" SortOrder="Ascending" />
                                            </SelectFields>
                                        </telerik:GridGroupByExpression>
                                    </GroupByExpressions>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar SLA {0}" CaptionDataField="Id">  
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <%--<FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle> --%>
                                        <FormMainTableStyle CellSpacing="0" CellPadding="3" Width="100%" /> 
                                        <FormTableStyle GridLines="Horizontal" CellSpacing="0" CellPadding="2" CssClass="module" Height="110px" Width="100%" /> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormStyle Width="100%" BackColor="#EEF2EA"></FormStyle> 
                                        <EditColumn EditText="Alterar" UpdateText="Confirmar" UniqueName="EditCommandColumn1" CancelText="Cancelar"></EditColumn> 
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings>
                                </MasterTableView>
                                <GroupingSettings CollapseTooltip="Recolher" ExpandTooltip="Expandir" GroupSplitDisplayFormat="Exibindo {0} de {1} itens." UnGroupButtonTooltip="Desagrupar" UnGroupTooltip="Arraste o item para fora da barra para desagrupar" />
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>                            
                            <asp:ObjectDataSource ID="ObjectDataSourceSLAs_Toner" runat="server" 
                                SelectMethod="SLA_EntregaInsumos" TypeName="CSFDigital.Controls.SLA">
                            </asp:ObjectDataSource>
                        </telerik:RadPageView>
                        <telerik:RadPageView ID="RadPageView4" runat="server">
                            <telerik:RadGrid ID="RadGrid5" runat="server" CellSpacing="0" 
                                GridLines="Horizontal"
                                AutoGenerateColumns="False" GroupingEnabled="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid5_NeedDataSource"
                                OnDeleteCommand="RadGrid5_DeleteCommand" 
                                OnInsertCommand="RadGrid5_InsertCommand" 
                                OnUpdateCommand="RadGrid5_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True" 
                                DataSourceID="ObjectDataSourceChaves">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp" 
                                    DataSourceID="ObjectDataSourceChaves">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar nova chave" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Valor" 
                                            FilterControlAltText="Filter Valor column" HeaderText="Valor" 
                                            SortExpression="Valor" UniqueName="Valor">
                                            <FooterStyle Width="250px" Wrap="False" />
                                            <HeaderStyle Width="250px" Wrap="False" />
                                            <ItemStyle Width="250px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="ValorAntigo" 
                                            FilterControlAltText="Filter ValorAntigo column" HeaderText="Valor Anterior" 
                                            SortExpression="ValorAntigo" UniqueName="ValorAntigo">
                                            <FooterStyle Width="250px" Wrap="False" />
                                            <HeaderStyle Width="250px" Wrap="False" />
                                            <ItemStyle Width="250px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Traducao" 
                                            FilterControlAltText="Filter Traducao column" HeaderText="Tradução" 
                                            SortExpression="Traducao" UniqueName="Traducao">
                                            <FooterStyle Width="250px" Wrap="False" />
                                            <HeaderStyle Width="250px" Wrap="False" />
                                            <ItemStyle Width="250px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridCheckBoxColumn DataField="Ativo" DataType="System.Boolean" 
                                            FilterControlAltText="Filter Ativo column" HeaderText="Ativo" 
                                            SortExpression="Ativo" UniqueName="Ativo">
                                        </telerik:GridCheckBoxColumn>
                                    </Columns>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar chave {0}" CaptionDataField="Valor">  
                                        <EditColumn CancelText="Cancelar" EditText="Alterar" 
                                            UniqueName="EditCommandColumn1" UpdateText="Confirmar">
                                        </EditColumn>
                                        <FormStyle BackColor="#EEF2EA" Width="100%" />
                                        <FormTableStyle CellPadding="2" CellSpacing="0" CssClass="module" GridLines="Horizontal" Height="110px" Width="100%" />
                                        <FormMainTableStyle CellPadding="3" CellSpacing="0" Width="100%" />
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings> 
                                </MasterTableView>
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>
                            <asp:ObjectDataSource ID="ObjectDataSourceChaves" runat="server" 
                                SelectMethod="RetornarChaves" TypeName="CSFDigital.Controls.Chave">
                            </asp:ObjectDataSource>
                        </telerik:RadPageView>
                        <telerik:RadPageView ID="RadPageView5" runat="server">
                                <telerik:RadGrid ID="RadGrid6" runat="server" CellSpacing="0" 
                                GridLines="Horizontal"
                                AutoGenerateColumns="False" 
                                AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
                                AutoGenerateEditColumn="True"
                                OnNeedDataSource="RadGrid6_NeedDataSource"
                                OnDeleteCommand="RadGrid6_DeleteCommand" 
                                OnInsertCommand="RadGrid6_InsertCommand" 
                                OnUpdateCommand="RadGrid6_UpdateCommand" EnableAJAX="True" 
                                AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" 
                                Culture="Portuguese (Brazil)" ShowStatusBar="True" 
                                DataSourceID="ObjectDataSourceFeriados" ShowGroupPanel="True">
                                <HeaderContextMenu CssClass="GridContextMenu_Default"></HeaderContextMenu>
                                <MasterTableView NoDetailRecordsText="Não há itens." 
                                    NoMasterRecordsText="Não há itens." 
                                    CommandItemDisplay="Top" 
                                    InsertItemDisplay="Bottom" EditMode="PopUp"
                                    DataSourceID="ObjectDataSourceFeriados">
                                    <CommandItemSettings ExportToPdfText="PDF" 
                                        AddNewRecordText="Adicionar novo feriado" ExportToCsvText="CSV" 
                                        ExportToExcelText="Excel" ExportToWordText="Word" RefreshText="Atualizar"></CommandItemSettings>
                                    <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                                    </RowIndicatorColumn>
                                    <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                                    </ExpandCollapseColumn>
                                    <Columns>
                                        <telerik:GridBoundColumn DataField="Estado" 
                                            FilterControlAltText="Filter Estado column" HeaderText="UF" 
                                            SortExpression="Estado" UniqueName="Estado">
                                            <FooterStyle Width="50px" Wrap="False" />
                                            <HeaderStyle Width="50px" Wrap="False" />
                                            <ItemStyle Width="50px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Cidade" 
                                            FilterControlAltText="Filter Cidade column" HeaderText="Cidade" 
                                            SortExpression="Cidade" UniqueName="Cidade">
                                            <FooterStyle Width="300px" Wrap="False" />
                                            <HeaderStyle Width="300px" Wrap="False" />
                                            <ItemStyle Width="300px" Wrap="False" />                                            
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="DataFeriado" 
                                            FilterControlAltText="Filter DataFeriado column" HeaderText="Data" 
                                            SortExpression="DataFeriado" UniqueName="DataFeriado" 
                                            DataType="System.DateTime" DataFormatString="{0:dd/MM/yyyy}">
                                            <FooterStyle Width="100px" Wrap="False" />
                                            <HeaderStyle Width="100px" Wrap="False" />
                                            <ItemStyle Width="100px" Wrap="False" />
                                        </telerik:GridBoundColumn>
                                        <telerik:GridBoundColumn DataField="Descricao" 
                                            FilterControlAltText="Filter Descricao column" HeaderText="Descrição" 
                                            SortExpression="Descricao" UniqueName="Descricao">
                                        </telerik:GridBoundColumn>
                                    </Columns>
                                    <GroupByExpressions>
                                        <telerik:GridGroupByExpression>
                                            <GroupByFields>
                                                <telerik:GridGroupByField  FieldAlias="Estado" FieldName="Estado" 
                                                    FormatString="" HeaderText="UF" SortOrder="Ascending" />
                                            </GroupByFields>
                                            <SelectFields>
                                                <telerik:GridGroupByField  FieldAlias="Estado" FieldName="Estado" 
                                                    FormatString="" HeaderText="UF" SortOrder="Ascending" />
                                            </SelectFields>
                                        </telerik:GridGroupByExpression>
                                    </GroupByExpressions>
                                    <EditFormSettings ColumnNumber="2" CaptionFormatString="Alterar feriado {0}" CaptionDataField="DataFeriado">  
                                        <EditColumn CancelText="Cancelar" EditText="Alterar" 
                                            UniqueName="EditCommandColumn1" UpdateText="Confirmar">
                                        </EditColumn>
                                        <FormStyle BackColor="#EEF2EA" Width="100%" />
                                        <FormTableStyle CellPadding="2" CellSpacing="0" CssClass="module" GridLines="Horizontal" Height="110px" Width="100%" />
                                        <FormMainTableStyle CellPadding="3" CellSpacing="0" Width="100%" />
                                        <FormTableItemStyle Wrap="False"></FormTableItemStyle> 
                                        <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle> 
                                        <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle> 
                                    </EditFormSettings> 
                                </MasterTableView>
                                <ClientSettings>
                                    <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                                </ClientSettings>
                                <FilterMenu EnableImageSprites="False"></FilterMenu>
                                <StatusBarSettings LoadingText="Carregando..." ReadyText="Pronto" />
                            </telerik:RadGrid>
                            <asp:ObjectDataSource ID="ObjectDataSourceFeriados" runat="server" 
                                SelectMethod="RetornaListaFeriados" TypeName="CSFDigital.Controls.Feriado">
                            </asp:ObjectDataSource>
                        </telerik:RadPageView>
                    </telerik:RadMultiPage>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
<asp:Content ID="Rodape" ContentPlaceHolderID="ContentPlaceHolderRodape" runat="server">
    <asp:UpdatePanel ID="UpdatePanelRodape" runat="server">
        <ContentTemplate>
            <asp:Timer ID="TimerInfoRodape" Interval="60000" runat="server" ontick="TimerInfoRodape_Tick"></asp:Timer>
            <asp:Label ID="lbInfoRodape" runat="server" Text="Espaço reservado ao cliente."></asp:Label>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>