//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parametros.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oids", Namespace="http://www.csfdigital.com.br/")]
    [System.SerializableAttribute()]
    public partial class Oids : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmwareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropriedadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPerfilField, value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fabricante {
            get {
                return this.FabricanteField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricanteField, value) != true)) {
                    this.FabricanteField = value;
                    this.RaisePropertyChanged("Fabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Firmware {
            get {
                return this.FirmwareField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmwareField, value) != true)) {
                    this.FirmwareField = value;
                    this.RaisePropertyChanged("Firmware");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Oid {
            get {
                return this.OidField;
            }
            set {
                if ((object.ReferenceEquals(this.OidField, value) != true)) {
                    this.OidField = value;
                    this.RaisePropertyChanged("Oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Propriedade {
            get {
                return this.PropriedadeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropriedadeField, value) != true)) {
                    this.PropriedadeField = value;
                    this.RaisePropertyChanged("Propriedade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilOID", Namespace="http://www.csfdigital.com.br/")]
    [System.SerializableAttribute()]
    public partial class PerfilOID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmwareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadastroOidPadraoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OidpadraoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdPerfil {
            get {
                return this.IdPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPerfilField, value) != true)) {
                    this.IdPerfilField = value;
                    this.RaisePropertyChanged("IdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Firmware {
            get {
                return this.FirmwareField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmwareField, value) != true)) {
                    this.FirmwareField = value;
                    this.RaisePropertyChanged("Firmware");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Fabricante {
            get {
                return this.FabricanteField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricanteField, value) != true)) {
                    this.FabricanteField = value;
                    this.RaisePropertyChanged("Fabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CadastroOidPadrao {
            get {
                return this.CadastroOidPadraoField;
            }
            set {
                if ((object.ReferenceEquals(this.CadastroOidPadraoField, value) != true)) {
                    this.CadastroOidPadraoField = value;
                    this.RaisePropertyChanged("CadastroOidPadrao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IdClasse {
            get {
                return this.IdClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClasseField, value) != true)) {
                    this.IdClasseField = value;
                    this.RaisePropertyChanged("IdClasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Oidpadrao {
            get {
                return this.OidpadraoField;
            }
            set {
                if ((object.ReferenceEquals(this.OidpadraoField, value) != true)) {
                    this.OidpadraoField = value;
                    this.RaisePropertyChanged("Oidpadrao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modelos", Namespace="http://www.csfdigital.com.br/")]
    [System.SerializableAttribute()]
    public partial class Modelos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firmwares", Namespace="http://www.csfdigital.com.br/")]
    [System.SerializableAttribute()]
    public partial class Firmwares : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFirmwareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Firmwares1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdFirmware {
            get {
                return this.IdFirmwareField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFirmwareField, value) != true)) {
                    this.IdFirmwareField = value;
                    this.RaisePropertyChanged("IdFirmware");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Firmwares1 {
            get {
                return this.Firmwares1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Firmwares1Field, value) != true)) {
                    this.Firmwares1Field = value;
                    this.RaisePropertyChanged("Firmwares1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.csfdigital.com.br/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.csfdigital.com.br/", ConfigurationName="WebService.DisparosSoap")]
    public interface DisparosSoap {
        
        // CODEGEN: Generating message contract since element name RetornaOidsResult from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaOids", ReplyAction="*")]
        Parametros.WebService.RetornaOidsResponse RetornaOids(Parametros.WebService.RetornaOidsRequest request);
        
        // CODEGEN: Generating message contract since element name fabricante from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaOidsParcial", ReplyAction="*")]
        Parametros.WebService.RetornaOidsParcialResponse RetornaOidsParcial(Parametros.WebService.RetornaOidsParcialRequest request);
        
        // CODEGEN: Generating message contract since element name RetornaPerfisResult from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaPerfis", ReplyAction="*")]
        Parametros.WebService.RetornaPerfisResponse RetornaPerfis(Parametros.WebService.RetornaPerfisRequest request);
        
        // CODEGEN: Generating message contract since element name disparo from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/CadastrarDisparo", ReplyAction="*")]
        Parametros.WebService.CadastrarDisparoResponse CadastrarDisparo(Parametros.WebService.CadastrarDisparoRequest request);
        
        // CODEGEN: Generating message contract since element name serie from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaIdEquipamento", ReplyAction="*")]
        Parametros.WebService.RetornaIdEquipamentoResponse RetornaIdEquipamento(Parametros.WebService.RetornaIdEquipamentoRequest request);
        
        // CODEGEN: Generating message contract since element name RetornaModelosResult from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaModelos", ReplyAction="*")]
        Parametros.WebService.RetornaModelosResponse RetornaModelos(Parametros.WebService.RetornaModelosRequest request);
        
        // CODEGEN: Generating message contract since element name fabricante from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaFirmwares", ReplyAction="*")]
        Parametros.WebService.RetornaFirmwaresResponse RetornaFirmwares(Parametros.WebService.RetornaFirmwaresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/retornaData", ReplyAction="*")]
        System.DateTime retornaData();
        
        // CODEGEN: Generating message contract since element name RetornaIdsDisparosResult from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaIdsDisparos", ReplyAction="*")]
        Parametros.WebService.RetornaIdsDisparosResponse RetornaIdsDisparos(Parametros.WebService.RetornaIdsDisparosRequest request);
        
        // CODEGEN: Generating message contract since element name RetornaDisparoResult from namespace http://www.csfdigital.com.br/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csfdigital.com.br/RetornaDisparo", ReplyAction="*")]
        Parametros.WebService.RetornaDisparoResponse RetornaDisparo(Parametros.WebService.RetornaDisparoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaOidsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaOids", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaOidsRequestBody Body;
        
        public RetornaOidsRequest() {
        }
        
        public RetornaOidsRequest(Parametros.WebService.RetornaOidsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornaOidsRequestBody {
        
        public RetornaOidsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaOidsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaOidsResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaOidsResponseBody Body;
        
        public RetornaOidsResponse() {
        }
        
        public RetornaOidsResponse(Parametros.WebService.RetornaOidsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaOidsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.Oids[] RetornaOidsResult;
        
        public RetornaOidsResponseBody() {
        }
        
        public RetornaOidsResponseBody(Parametros.WebService.Oids[] RetornaOidsResult) {
            this.RetornaOidsResult = RetornaOidsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaOidsParcialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaOidsParcial", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaOidsParcialRequestBody Body;
        
        public RetornaOidsParcialRequest() {
        }
        
        public RetornaOidsParcialRequest(Parametros.WebService.RetornaOidsParcialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaOidsParcialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fabricante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firmware;
        
        public RetornaOidsParcialRequestBody() {
        }
        
        public RetornaOidsParcialRequestBody(string fabricante, string modelo, string firmware) {
            this.fabricante = fabricante;
            this.modelo = modelo;
            this.firmware = firmware;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaOidsParcialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaOidsParcialResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaOidsParcialResponseBody Body;
        
        public RetornaOidsParcialResponse() {
        }
        
        public RetornaOidsParcialResponse(Parametros.WebService.RetornaOidsParcialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaOidsParcialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.Oids[] RetornaOidsParcialResult;
        
        public RetornaOidsParcialResponseBody() {
        }
        
        public RetornaOidsParcialResponseBody(Parametros.WebService.Oids[] RetornaOidsParcialResult) {
            this.RetornaOidsParcialResult = RetornaOidsParcialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaPerfisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaPerfis", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaPerfisRequestBody Body;
        
        public RetornaPerfisRequest() {
        }
        
        public RetornaPerfisRequest(Parametros.WebService.RetornaPerfisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornaPerfisRequestBody {
        
        public RetornaPerfisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaPerfisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaPerfisResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaPerfisResponseBody Body;
        
        public RetornaPerfisResponse() {
        }
        
        public RetornaPerfisResponse(Parametros.WebService.RetornaPerfisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaPerfisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.PerfilOID[] RetornaPerfisResult;
        
        public RetornaPerfisResponseBody() {
        }
        
        public RetornaPerfisResponseBody(Parametros.WebService.PerfilOID[] RetornaPerfisResult) {
            this.RetornaPerfisResult = RetornaPerfisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarDisparoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarDisparo", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.CadastrarDisparoRequestBody Body;
        
        public CadastrarDisparoRequest() {
        }
        
        public CadastrarDisparoRequest(Parametros.WebService.CadastrarDisparoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class CadastrarDisparoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string disparo;
        
        public CadastrarDisparoRequestBody() {
        }
        
        public CadastrarDisparoRequestBody(string disparo) {
            this.disparo = disparo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarDisparoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarDisparoResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.CadastrarDisparoResponseBody Body;
        
        public CadastrarDisparoResponse() {
        }
        
        public CadastrarDisparoResponse(Parametros.WebService.CadastrarDisparoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CadastrarDisparoResponseBody {
        
        public CadastrarDisparoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaIdEquipamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaIdEquipamento", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaIdEquipamentoRequestBody Body;
        
        public RetornaIdEquipamentoRequest() {
        }
        
        public RetornaIdEquipamentoRequest(Parametros.WebService.RetornaIdEquipamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaIdEquipamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serie;
        
        public RetornaIdEquipamentoRequestBody() {
        }
        
        public RetornaIdEquipamentoRequestBody(string serie) {
            this.serie = serie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaIdEquipamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaIdEquipamentoResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaIdEquipamentoResponseBody Body;
        
        public RetornaIdEquipamentoResponse() {
        }
        
        public RetornaIdEquipamentoResponse(Parametros.WebService.RetornaIdEquipamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaIdEquipamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RetornaIdEquipamentoResult;
        
        public RetornaIdEquipamentoResponseBody() {
        }
        
        public RetornaIdEquipamentoResponseBody(int RetornaIdEquipamentoResult) {
            this.RetornaIdEquipamentoResult = RetornaIdEquipamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaModelosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaModelos", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaModelosRequestBody Body;
        
        public RetornaModelosRequest() {
        }
        
        public RetornaModelosRequest(Parametros.WebService.RetornaModelosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornaModelosRequestBody {
        
        public RetornaModelosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaModelosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaModelosResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaModelosResponseBody Body;
        
        public RetornaModelosResponse() {
        }
        
        public RetornaModelosResponse(Parametros.WebService.RetornaModelosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaModelosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.Modelos[] RetornaModelosResult;
        
        public RetornaModelosResponseBody() {
        }
        
        public RetornaModelosResponseBody(Parametros.WebService.Modelos[] RetornaModelosResult) {
            this.RetornaModelosResult = RetornaModelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaFirmwaresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaFirmwares", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaFirmwaresRequestBody Body;
        
        public RetornaFirmwaresRequest() {
        }
        
        public RetornaFirmwaresRequest(Parametros.WebService.RetornaFirmwaresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaFirmwaresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fabricante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string modelo;
        
        public RetornaFirmwaresRequestBody() {
        }
        
        public RetornaFirmwaresRequestBody(string fabricante, string modelo) {
            this.fabricante = fabricante;
            this.modelo = modelo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaFirmwaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaFirmwaresResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaFirmwaresResponseBody Body;
        
        public RetornaFirmwaresResponse() {
        }
        
        public RetornaFirmwaresResponse(Parametros.WebService.RetornaFirmwaresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaFirmwaresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.Firmwares[] RetornaFirmwaresResult;
        
        public RetornaFirmwaresResponseBody() {
        }
        
        public RetornaFirmwaresResponseBody(Parametros.WebService.Firmwares[] RetornaFirmwaresResult) {
            this.RetornaFirmwaresResult = RetornaFirmwaresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaIdsDisparosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaIdsDisparos", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaIdsDisparosRequestBody Body;
        
        public RetornaIdsDisparosRequest() {
        }
        
        public RetornaIdsDisparosRequest(Parametros.WebService.RetornaIdsDisparosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornaIdsDisparosRequestBody {
        
        public RetornaIdsDisparosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaIdsDisparosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaIdsDisparosResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaIdsDisparosResponseBody Body;
        
        public RetornaIdsDisparosResponse() {
        }
        
        public RetornaIdsDisparosResponse(Parametros.WebService.RetornaIdsDisparosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaIdsDisparosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Parametros.WebService.ArrayOfString RetornaIdsDisparosResult;
        
        public RetornaIdsDisparosResponseBody() {
        }
        
        public RetornaIdsDisparosResponseBody(Parametros.WebService.ArrayOfString RetornaIdsDisparosResult) {
            this.RetornaIdsDisparosResult = RetornaIdsDisparosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaDisparoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaDisparo", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaDisparoRequestBody Body;
        
        public RetornaDisparoRequest() {
        }
        
        public RetornaDisparoRequest(Parametros.WebService.RetornaDisparoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaDisparoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDisparo;
        
        public RetornaDisparoRequestBody() {
        }
        
        public RetornaDisparoRequestBody(int idDisparo) {
            this.idDisparo = idDisparo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornaDisparoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornaDisparoResponse", Namespace="http://www.csfdigital.com.br/", Order=0)]
        public Parametros.WebService.RetornaDisparoResponseBody Body;
        
        public RetornaDisparoResponse() {
        }
        
        public RetornaDisparoResponse(Parametros.WebService.RetornaDisparoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.csfdigital.com.br/")]
    public partial class RetornaDisparoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornaDisparoResult;
        
        public RetornaDisparoResponseBody() {
        }
        
        public RetornaDisparoResponseBody(string RetornaDisparoResult) {
            this.RetornaDisparoResult = RetornaDisparoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DisparosSoapChannel : Parametros.WebService.DisparosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisparosSoapClient : System.ServiceModel.ClientBase<Parametros.WebService.DisparosSoap>, Parametros.WebService.DisparosSoap {
        
        public DisparosSoapClient() {
        }
        
        public DisparosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisparosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisparosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisparosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaOidsResponse Parametros.WebService.DisparosSoap.RetornaOids(Parametros.WebService.RetornaOidsRequest request) {
            return base.Channel.RetornaOids(request);
        }
        
        public Parametros.WebService.Oids[] RetornaOids() {
            Parametros.WebService.RetornaOidsRequest inValue = new Parametros.WebService.RetornaOidsRequest();
            inValue.Body = new Parametros.WebService.RetornaOidsRequestBody();
            Parametros.WebService.RetornaOidsResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaOids(inValue);
            return retVal.Body.RetornaOidsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaOidsParcialResponse Parametros.WebService.DisparosSoap.RetornaOidsParcial(Parametros.WebService.RetornaOidsParcialRequest request) {
            return base.Channel.RetornaOidsParcial(request);
        }
        
        public Parametros.WebService.Oids[] RetornaOidsParcial(string fabricante, string modelo, string firmware) {
            Parametros.WebService.RetornaOidsParcialRequest inValue = new Parametros.WebService.RetornaOidsParcialRequest();
            inValue.Body = new Parametros.WebService.RetornaOidsParcialRequestBody();
            inValue.Body.fabricante = fabricante;
            inValue.Body.modelo = modelo;
            inValue.Body.firmware = firmware;
            Parametros.WebService.RetornaOidsParcialResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaOidsParcial(inValue);
            return retVal.Body.RetornaOidsParcialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaPerfisResponse Parametros.WebService.DisparosSoap.RetornaPerfis(Parametros.WebService.RetornaPerfisRequest request) {
            return base.Channel.RetornaPerfis(request);
        }
        
        public Parametros.WebService.PerfilOID[] RetornaPerfis() {
            Parametros.WebService.RetornaPerfisRequest inValue = new Parametros.WebService.RetornaPerfisRequest();
            inValue.Body = new Parametros.WebService.RetornaPerfisRequestBody();
            Parametros.WebService.RetornaPerfisResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaPerfis(inValue);
            return retVal.Body.RetornaPerfisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.CadastrarDisparoResponse Parametros.WebService.DisparosSoap.CadastrarDisparo(Parametros.WebService.CadastrarDisparoRequest request) {
            return base.Channel.CadastrarDisparo(request);
        }
        
        public void CadastrarDisparo(string disparo) {
            Parametros.WebService.CadastrarDisparoRequest inValue = new Parametros.WebService.CadastrarDisparoRequest();
            inValue.Body = new Parametros.WebService.CadastrarDisparoRequestBody();
            inValue.Body.disparo = disparo;
            Parametros.WebService.CadastrarDisparoResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).CadastrarDisparo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaIdEquipamentoResponse Parametros.WebService.DisparosSoap.RetornaIdEquipamento(Parametros.WebService.RetornaIdEquipamentoRequest request) {
            return base.Channel.RetornaIdEquipamento(request);
        }
        
        public int RetornaIdEquipamento(string serie) {
            Parametros.WebService.RetornaIdEquipamentoRequest inValue = new Parametros.WebService.RetornaIdEquipamentoRequest();
            inValue.Body = new Parametros.WebService.RetornaIdEquipamentoRequestBody();
            inValue.Body.serie = serie;
            Parametros.WebService.RetornaIdEquipamentoResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaIdEquipamento(inValue);
            return retVal.Body.RetornaIdEquipamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaModelosResponse Parametros.WebService.DisparosSoap.RetornaModelos(Parametros.WebService.RetornaModelosRequest request) {
            return base.Channel.RetornaModelos(request);
        }
        
        public Parametros.WebService.Modelos[] RetornaModelos() {
            Parametros.WebService.RetornaModelosRequest inValue = new Parametros.WebService.RetornaModelosRequest();
            inValue.Body = new Parametros.WebService.RetornaModelosRequestBody();
            Parametros.WebService.RetornaModelosResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaModelos(inValue);
            return retVal.Body.RetornaModelosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaFirmwaresResponse Parametros.WebService.DisparosSoap.RetornaFirmwares(Parametros.WebService.RetornaFirmwaresRequest request) {
            return base.Channel.RetornaFirmwares(request);
        }
        
        public Parametros.WebService.Firmwares[] RetornaFirmwares(string fabricante, string modelo) {
            Parametros.WebService.RetornaFirmwaresRequest inValue = new Parametros.WebService.RetornaFirmwaresRequest();
            inValue.Body = new Parametros.WebService.RetornaFirmwaresRequestBody();
            inValue.Body.fabricante = fabricante;
            inValue.Body.modelo = modelo;
            Parametros.WebService.RetornaFirmwaresResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaFirmwares(inValue);
            return retVal.Body.RetornaFirmwaresResult;
        }
        
        public System.DateTime retornaData() {
            return base.Channel.retornaData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaIdsDisparosResponse Parametros.WebService.DisparosSoap.RetornaIdsDisparos(Parametros.WebService.RetornaIdsDisparosRequest request) {
            return base.Channel.RetornaIdsDisparos(request);
        }
        
        public Parametros.WebService.ArrayOfString RetornaIdsDisparos() {
            Parametros.WebService.RetornaIdsDisparosRequest inValue = new Parametros.WebService.RetornaIdsDisparosRequest();
            inValue.Body = new Parametros.WebService.RetornaIdsDisparosRequestBody();
            Parametros.WebService.RetornaIdsDisparosResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaIdsDisparos(inValue);
            return retVal.Body.RetornaIdsDisparosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parametros.WebService.RetornaDisparoResponse Parametros.WebService.DisparosSoap.RetornaDisparo(Parametros.WebService.RetornaDisparoRequest request) {
            return base.Channel.RetornaDisparo(request);
        }
        
        public string RetornaDisparo(int idDisparo) {
            Parametros.WebService.RetornaDisparoRequest inValue = new Parametros.WebService.RetornaDisparoRequest();
            inValue.Body = new Parametros.WebService.RetornaDisparoRequestBody();
            inValue.Body.idDisparo = idDisparo;
            Parametros.WebService.RetornaDisparoResponse retVal = ((Parametros.WebService.DisparosSoap)(this)).RetornaDisparo(inValue);
            return retVal.Body.RetornaDisparoResult;
        }
    }
}
