//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebEmailMonitor.wsEmail {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Threading.Tasks;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmailsPendentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPendentesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WebEmailMonitor.Properties.Settings.Default.WebEmailMonitor_wsEmail_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarEmailCompletedEventHandler EnviarEmailCompleted;
        
        /// <remarks/>
        public event ListarEmailsPendentesCompletedEventHandler ListarEmailsPendentesCompleted;
        
        /// <remarks/>
        public event ListarPendentesCompletedEventHandler ListarPendentesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarEmail(string para, string copia, string copiaOculta, string titulo, string mensagem, bool html) {
            this.Invoke("EnviarEmail", new object[] {
                        para,
                        copia,
                        copiaOculta,
                        titulo,
                        mensagem,
                        html});
        }
        
        /// <remarks/>
        public void EnviarEmailAsync(string para, string copia, string copiaOculta, string titulo, string mensagem, bool html) {
            this.EnviarEmailAsync(para, copia, copiaOculta, titulo, mensagem, html, null);
        }
        
        /// <remarks/>
        public void EnviarEmailAsync(string para, string copia, string copiaOculta, string titulo, string mensagem, bool html, object userState) {
            if ((this.EnviarEmailOperationCompleted == null)) {
                this.EnviarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarEmailOperationCompleted);
            }
            this.InvokeAsync("EnviarEmail", new object[] {
                        para,
                        copia,
                        copiaOculta,
                        titulo,
                        mensagem,
                        html}, this.EnviarEmailOperationCompleted, userState);
        }
        
        private void OnEnviarEmailOperationCompleted(object arg) {
            if ((this.EnviarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEmailsPendentes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ListarEmailsPendentes(string chave) {
            object[] results = this.Invoke("ListarEmailsPendentes", new object[] {
                        chave});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmailsPendentesAsync(string chave) {
            this.ListarEmailsPendentesAsync(chave, null);
        }
        
        /// <remarks/>
        public void ListarEmailsPendentesAsync(string chave, object userState) {
            if ((this.ListarEmailsPendentesOperationCompleted == null)) {
                this.ListarEmailsPendentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmailsPendentesOperationCompleted);
            }
            this.InvokeAsync("ListarEmailsPendentes", new object[] {
                        chave}, this.ListarEmailsPendentesOperationCompleted, userState);
        }
        
        private void OnListarEmailsPendentesOperationCompleted(object arg) {
            if ((this.ListarEmailsPendentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmailsPendentesCompleted(this, new ListarEmailsPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPendentes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Email[] ListarPendentes(string chave) {
            object[] results = this.Invoke("ListarPendentes", new object[] {
                        chave});
            return ((Email[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPendentesAsync(string chave) {
            this.ListarPendentesAsync(chave, null);
        }
        
        /// <remarks/>
        public void ListarPendentesAsync(string chave, object userState) {
            if ((this.ListarPendentesOperationCompleted == null)) {
                this.ListarPendentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPendentesOperationCompleted);
            }
            this.InvokeAsync("ListarPendentes", new object[] {
                        chave}, this.ListarPendentesOperationCompleted, userState);
        }
        
        private void OnListarPendentesOperationCompleted(object arg) {
            if ((this.ListarPendentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPendentesCompleted(this, new ListarPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }

        internal Task<Email[]> ListarPendentes()
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Email {
        
        private string paraField;
        
        private string copiaField;
        
        private string copiaOcultaField;
        
        private string tituloField;
        
        private string mensagemField;
        
        private bool htmlField;
        
        private string idEmailField;
        
        /// <remarks/>
        public string Para {
            get {
                return this.paraField;
            }
            set {
                this.paraField = value;
            }
        }
        
        /// <remarks/>
        public string Copia {
            get {
                return this.copiaField;
            }
            set {
                this.copiaField = value;
            }
        }
        
        /// <remarks/>
        public string CopiaOculta {
            get {
                return this.copiaOcultaField;
            }
            set {
                this.copiaOcultaField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        public string IdEmail {
            get {
                return this.idEmailField;
            }
            set {
                this.idEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EnviarEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarEmailsPendentesCompletedEventHandler(object sender, ListarEmailsPendentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmailsPendentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmailsPendentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarPendentesCompletedEventHandler(object sender, ListarPendentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPendentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPendentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Email[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Email[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591