//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnaprint.Testes.dnaPrintWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="dnaPrintWS.IAgente")]
    public interface IAgente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgente/Ativo", ReplyAction="http://tempuri.org/IAgente/AtivoResponse")]
        bool Ativo(string key, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgente/Ativo", ReplyAction="http://tempuri.org/IAgente/AtivoResponse")]
        System.Threading.Tasks.Task<bool> AtivoAsync(string key, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgente/Adicionar", ReplyAction="http://tempuri.org/IAgente/AdicionarResponse")]
        bool Adicionar(string key, string computador, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgente/Adicionar", ReplyAction="http://tempuri.org/IAgente/AdicionarResponse")]
        System.Threading.Tasks.Task<bool> AdicionarAsync(string key, string computador, string serie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgenteChannel : dnaprint.Testes.dnaPrintWS.IAgente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgenteClient : System.ServiceModel.ClientBase<dnaprint.Testes.dnaPrintWS.IAgente>, dnaprint.Testes.dnaPrintWS.IAgente {
        
        public AgenteClient() {
        }
        
        public AgenteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgenteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ativo(string key, string serie) {
            return base.Channel.Ativo(key, serie);
        }
        
        public System.Threading.Tasks.Task<bool> AtivoAsync(string key, string serie) {
            return base.Channel.AtivoAsync(key, serie);
        }
        
        public bool Adicionar(string key, string computador, string serie) {
            return base.Channel.Adicionar(key, computador, serie);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarAsync(string key, string computador, string serie) {
            return base.Channel.AdicionarAsync(key, computador, serie);
        }
    }
}
